version: '3.3'
services:
  db:
    image: 'postgres:16'
    ports:
      - '127.0.0.1:${CCD_LOCAL_DB_PORT}:5432'
    environment:
        - POSTGRES_PASSWORD=pwd
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d/
      #- ./postgres-data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql.conf