server:
    port: 8080
    error:
        include-stacktrace: "always"

spring:
    datasource:
        url: "jdbc:postgresql://db:5432/charlyday"
        username: "postgres"
        password: "pwd"
        driver-class-name: "org.postgresql.Driver"
    jpa:
        properties: 
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQLDialect"
                format_sql: "true"
        show-sql: "false"

management:
    endpoint:
        health:
            show-details: "always"

logging:
    level:
        charlyday:
            ccd: "DEBUG"

security:
    jwt:
        secret-key: cb5d4f92af1550dca925f3ec9e4622aa3dda7b6c3fe09e9c0c666fcebcebea9a
        expiration-time: 3600000